name: flutter_barcode_scanner
description: A plugin for barcode scanning support on Android and iOS. Supports barcodes, QR codes, etc.
version: 3.0.0
author: Amol Gangadhare <amol.gangadhare@gmail.com>
homepage: https://github.com/AmolGangadhare/flutter_barcode_scanner

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8
  flutter_plugin_android_lifecycle: ^2.0.24
dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.1

flutter:
  # This section identifies this Flutter project as a plugin project.
  # The androidPackage and pluginClass identifiers should not ordinarily
  # be modified. They are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      android:
        package: com.amolg.flutterbarcodescanner
        pluginClass: FlutterBarcodeScannerPlugin
      ios:
        pluginClass: SwiftFlutterBarcodeScannerPlugin